<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-NUE1PJR8" ignored="0" name="UsersTest" tests="5" failures="1" timestamp="19 Sep 2022 10:03:45 GMT" time="8.615" errors="0">
  <testcase name="countOfMaleUsers" time="0.868" classname="userpgtest.UserPgTest"/>
  <testcase name="varifyMobileNoOfUsers" time="2.727" classname="userpgtest.UserPgTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at userpgtest.UserPgTest.varifyMobileNoOfUsers(UserPgTest.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- varifyMobileNoOfUsers -->
  <testcase name="varifyMahaStateOccur" time="2.334" classname="userpgtest.UserPgTest"/>
  <testcase name="varifyMailsOfMahaState" time="2.282" classname="userpgtest.UserPgTest"/>
  <testcase name="veriryOperatorsPgLoad" time="0.22" classname="userpgtest.UserPgTest"/>
</testsuite> <!-- UsersTest -->
