<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-NUE1PJR8" ignored="0" name="UserpgTest" tests="5" failures="1" timestamp="04 Oct 2022 11:33:22 GMT" time="7.616" errors="0">
  <testcase name="countOfMaleUsers" time="0.819" classname="userpgtest.UserPgTest"/>
  <testcase name="varifyMobileNoOfUsers" time="2.27" classname="userpgtest.UserPgTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at userpgtest.UserPgTest.varifyMobileNoOfUsers(UserPgTest.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- varifyMobileNoOfUsers -->
  <testcase name="varifyMahaStateOccur" time="2.121" classname="userpgtest.UserPgTest"/>
  <testcase name="varifyMailsOfMahaState" time="2.102" classname="userpgtest.UserPgTest"/>
  <testcase name="veriryOperatorsPgLoad" time="0.157" classname="userpgtest.UserPgTest"/>
</testsuite> <!-- UserpgTest -->
